# Generated by Django 5.2.1 on 2025-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-searched_at",),
            },
        ),
    ]
